/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModelsBookPopularityStat } from '../../models/models-book-popularity-stat';

export interface BookPopularityStats$Params {
}

export function bookPopularityStats(http: HttpClient, rootUrl: string, params?: BookPopularityStats$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ModelsBookPopularityStat>>> {
  const rb = new RequestBuilder(rootUrl, bookPopularityStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ModelsBookPopularityStat>>;
    })
  );
}

bookPopularityStats.PATH = '/api/dashboard/bookPopularityStats';
