/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModelsTrueFalse } from '../../models/models-true-false';

export interface IsUserReviewBeingApproved$Params {
  id: number;
}

export function isUserReviewBeingApproved(http: HttpClient, rootUrl: string, params: IsUserReviewBeingApproved$Params, context?: HttpContext): Observable<StrictHttpResponse<ModelsTrueFalse>> {
  const rb = new RequestBuilder(rootUrl, isUserReviewBeingApproved.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ModelsTrueFalse>;
    })
  );
}

isUserReviewBeingApproved.PATH = '/api/review/customer/isBeingApproved';
