/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModelsReview } from '../../models/models-review';

export interface GetReviewsToApprove$Params {
}

export function getReviewsToApprove(http: HttpClient, rootUrl: string, params?: GetReviewsToApprove$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ModelsReview>>> {
  const rb = new RequestBuilder(rootUrl, getReviewsToApprove.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ModelsReview>>;
    })
  );
}

getReviewsToApprove.PATH = '/api/review/management/toApprove';
