/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApproveReviewInput } from './models/approve-review-input';
export type { CreateAuthorInput } from './models/create-author-input';
export type { CreateBookInput } from './models/create-book-input';
export type { CreateGenreInput } from './models/create-genre-input';
export type { CreateReviewInput } from './models/create-review-input';
export type { CreateUserInput } from './models/create-user-input';
export type { LoginInput } from './models/login-input';
export type { ModelsAuthor } from './models/models-author';
export type { ModelsBook } from './models/models-book';
export type { ModelsBookPopularityStat } from './models/models-book-popularity-stat';
export type { ModelsBookStat } from './models/models-book-stat';
export type { ModelsCustomerActivity } from './models/models-customer-activity';
export type { ModelsGenre } from './models/models-genre';
export type { ModelsLoginResponse } from './models/models-login-response';
export type { ModelsReview } from './models/models-review';
export type { ModelsTrueFalse } from './models/models-true-false';
export type { ModelsUser } from './models/models-user';
export type { RegisterInput } from './models/register-input';
export type { UpdateBookInput } from './models/update-book-input';
export type { UpdateUserInput } from './models/update-user-input';
