/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationService } from './services/authentication.service';
export type { AuthorService } from './services/author.service';
export type { AuthorManagementService } from './services/author-management.service';
export type { BookService } from './services/book.service';
export type { BookManagementService } from './services/book-management.service';
export type { CartService } from './services/cart.service';
export type { GenreService } from './services/genre.service';
export type { GenreManagementService } from './services/genre-management.service';
export type { UserManagementService } from './services/user-management.service';
export type { UserService } from './services/user.service';
export type { WishlistService } from './services/wishlist.service';
