/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModelsCount } from '../../models/models-count';

export interface GetCartCount$Params {
}

export function getCartCount(http: HttpClient, rootUrl: string, params?: GetCartCount$Params, context?: HttpContext): Observable<StrictHttpResponse<ModelsCount>> {
  const rb = new RequestBuilder(rootUrl, getCartCount.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ModelsCount>;
    })
  );
}

getCartCount.PATH = '/api/cart/count';
