/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModelsBook } from '../models/models-book';
import { ModelsUser } from '../models/models-user';
export interface ModelsReview {
  approved: boolean;
  book: ModelsBook;
  id: number;
  stars: number;
  text: string;
  user: ModelsUser;
}
