/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModelsUser } from '../models/models-user';
export interface ModelsReview {
  approved: boolean;
  bookId: number;
  id: number;
  stars: number;
  text: string;
  user: ModelsUser;
  userId: number;
}
