/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModelsAuthor } from '../models/models-author';
import { ModelsGenre } from '../models/models-genre';
export interface ModelsBook {
  author: ModelsAuthor;
  averageRating: number;
  genres: Array<ModelsGenre>;
  hasImage: boolean;
  id: number;
  isbn: string;
  name: string;
  price: number;
  published: string;
  summary: string;
}
