/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsAuthor {
  birth: string;
  firstName: string;
  id: number;
  lastName: string;
}
