/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsBookPopularityStat {
  author_name?: string;
  average_rating?: number;
  book_id?: string;
  book_name?: string;
  genre_name?: string;
  total_reviews?: number;
}
