/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsDiscount {
  code: string;
  id: number;
  price: number;
  used: boolean;
  userId: number;
  validUntil: string;
}
