/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsBookStat {
  authorName?: string;
  averageRating?: number;
  bookId?: number;
  bookName?: string;
  totalRevenue?: number;
  totalReviews?: number;
  totalSales?: number;
}
