/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsUser {
  firstName: string;
  id: number;
  lastName: string;
  mail: string;
  points: number;
  role: string;
}
