/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsCustomerActivity {
  email?: string;
  fullName?: string;
  points?: number;
  totalCartBooks?: number;
  totalOrders?: number;
  totalReviews?: number;
  totalSpent?: number;
  totalWishlistBooks?: number;
  userId?: number;
}
