/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModelsAddress {
  city: string;
  id: number;
  postCode: number;
  street: string;
  userId: number;
}
