/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModelsAddress } from '../models/models-address';
import { ModelsBook } from '../models/models-book';
import { ModelsDiscount } from '../models/models-discount';
export interface ModelsOrder {
  address: ModelsAddress;
  addressId: number;
  createdAt: string;
  discount?: ModelsDiscount;
  id: number;
  orderedBooks: Array<ModelsBook>;
  status: string;
  totalPrice: number;
  userId: number;
}
