/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterInput {
  firstName: string;
  lastName: string;
  mail: string;
  password: string;
}
