/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserInput {
  firstName?: string | null;
  id: number;
  lastName?: string | null;
  mail?: string | null;
  password?: string | null;
}
