/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBookInput {
  authorId: number;
  genreIds: Array<number>;
  id: number;
  isbn: string;
  name: string;
  price: number;
  published: string;
  summary: string;
}
