/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createReview } from '../fn/customer-review/create-review';
import { CreateReview$Params } from '../fn/customer-review/create-review';


/**
 * Recenze zákazníka
 */
@Injectable({ providedIn: 'root' })
export class CustomerReviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createReview()` */
  static readonly CreateReviewPath = '/api/review/customer';

  /**
   * Vytvoření recenze.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReview$Response(params?: CreateReview$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return createReview(this.http, this.rootUrl, params, context);
  }

  /**
   * Vytvoření recenze.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReview(params?: CreateReview$Params, context?: HttpContext): Observable<void> {
    return this.createReview$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
