/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getApprovedReviewsByBookId } from '../fn/review/get-approved-reviews-by-book-id';
import { GetApprovedReviewsByBookId$Params } from '../fn/review/get-approved-reviews-by-book-id';
import { ModelsReview } from '../models/models-review';


/**
 * Recenze
 */
@Injectable({ providedIn: 'root' })
export class ReviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getApprovedReviewsByBookId()` */
  static readonly GetApprovedReviewsByBookIdPath = '/api/review/all';

  /**
   * Všechny schválené recenze podle knihy.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getApprovedReviewsByBookId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApprovedReviewsByBookId$Response(params: GetApprovedReviewsByBookId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ModelsReview>>> {
    return getApprovedReviewsByBookId(this.http, this.rootUrl, params, context);
  }

  /**
   * Všechny schválené recenze podle knihy.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getApprovedReviewsByBookId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApprovedReviewsByBookId(params: GetApprovedReviewsByBookId$Params, context?: HttpContext): Observable<Array<ModelsReview>> {
    return this.getApprovedReviewsByBookId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ModelsReview>>): Array<ModelsReview> => r.body)
    );
  }

}
